[package]
name = "solana-escrow"
version = "0.2.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.7.11"
thiserror = "1.0.24"
<<<<<<< HEAD
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}
=======
>>>>>>> 1a36c4af2ead0e083ffe9db40a11dac858ddc1fd

[lib]
crate-type = ["cdylib", "lib"]
